#!/bin/bash

set -e

# Retrieve arguments
username=$1

# Source app helpers
source /usr/share/yunohost/helpers

# Set app specific variables
# TODO: Use real db user and pass, impossible due to the lock
app=#APP#
dbname=$app
dbuser=root
dbpass=$(sudo cat /etc/yunohost/mysql)

_query() {
    mysql -B -s -r -u "$dbuser" --password="$dbpass" "$dbname" <<< "$1"
}

# Calculate user id and random password
last_id=$(_query "SELECT id FROM users ORDER BY id DESC LIMIT 1")
user_id=$((last_id + 1))
user_pass=$(ynh_string_random)

# Create new user entry
ynh_mysql_connect_as "$dbuser" "$dbpass" "$dbname" << EOF
INSERT INTO users (id,username,password,name,email)
  VALUES ('${user_id}','${username}','${user_pass}','${username}','');
INSERT INTO users_config (user_id,name,value)
  VALUES ('${user_id}','language','en_EN.utf8');
INSERT INTO users_config (user_id,name,value)
  VALUES ('${user_id}','pager','10');
EOF
