#!/bin/bash

db_user=wallabag
db_name=wallabag
root_pwd=$(sudo cat /etc/yunohost/mysql)
passwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{40\}\).*/\1/p')
user=$1
mysql -u root -p$root_pwd $db_name -e "select MAX(id) from users INTO OUTFILE '/tmp/useridwallabag';"
id=$(cat /tmp/useridwallabag)

mysql -u root -p$root_pwd $db_name -e "insert into users (id,username,password,name,email) values ('','$user','$passwd','$user','');"
mysql -u root -p$root_pwd $db_name -e "insert into users_config (id,user_id,name,value) values ('','$id','pager','10');"
mysql -u root -p$root_pwd $db_name -e "insert into users_config (id,user_id,name,value) values ('','$id','language','en_EN.utf8');"
mysql -u root -p$root_pwd $db_name -e "insert into users_config (id,user_id,name,value) values ('','$id','theme','baggy');"

rm /tmp/useridwallabag

