#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a wallabag
if [[ ! $? -eq 0 ]]; then
exit 1
fi

# Generate random password
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use 'wallabag' as database name and user
db_user=wallabag

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd -s $(readlink -e ../sources/install/mysql.sql)
sudo yunohost app setting wallabag mysqlpwd -v $db_pwd

# Copy files to the right place
final_path=/var/www/wallabag
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path
sudo unzip ../sources/vendor.zip -d $final_path

# Set permissions to roundcube directory
sudo chown -R www-data: $final_path

# Configuration
sudo cp ../conf/config.inc.php $final_path/inc/poche/
sudo sed -i "s/yunouser/$db_user/g" $final_path/inc/poche/config.inc.php
sudo sed -i "s/yunopass/$db_pwd/g" $final_path/inc/poche/config.inc.php
sudo sed -i "s/yunobase/$db_user/g" $final_path/inc/poche/config.inc.php
j=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{40\}\).*/\1/p')
sudo sed -i "s/KEY1/$j/g" $final_path/inc/poche/config.inc.php
sudo rm -Rf $final_path/install

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf*
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf*
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/wallabag.conf

# Add users
wallabag_users=$(ldapsearch -h localhost -b ou=users,dc=yunohost,dc=org -x objectClass=mailAccount uid | grep uid: | sed 's/uid: //' | xargs)
id=1
for walluser in $wallabag_users
do
    password=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{40\}\).*/\1/p')
    mysql -u $db_user -p$db_pwd $db_user -e "insert into users (id,username,password,name,email) values ('','$walluser','$passwd','$walluser','');"
    mysql -u $db_user -p$db_pwd $db_user -e "insert into users_config (id,user_id,name,value) values ('','$id','pager','10');"
    mysql -u $db_user -p$db_pwd $db_user -e "insert into users_config (id,user_id,name,value) values ('','$id','language','en_EN.utf8');"
    mysql -u $db_user -p$db_pwd $db_user -e "insert into users_config (id,user_id,name,value) values ('','$id','theme','baggy');"
    ((id++)) 
done


# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
