#!/bin/bash

set -e

# Retrieve arguments
domain=$1
path=${2%/}
app=${!#}

# Load common variables and helpers
source ./_common.sh

# INSTALL DEPENDENCIES
ynh_install_app_dependencies "$PKG_DEPENDENCIES"

# Set app specific variables
dbname=$app
dbuser=$app

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app \
  || exit 1

# Check destination directory
DESTDIR="/var/www/${app}"
[[ -d "$DESTDIR" ]] && ynh_die \
"The destination directory '${DESTDIR}' already exists.\
 You should safely delete it before installing this app."

# Create tmp directory and fetch app inside
TMPDIR=$(ynh_mkdir_tmp)
init_wallabag "$TMPDIR"

# Generate random DES key & password
deskey=$(ynh_string_random 24)
dbpass=$(ynh_string_random)

# Initialize database
ynh_mysql_create_db "$dbname" "$dbuser" "$dbpass"
ynh_mysql_connect_as "$dbuser" "$dbpass" "$dbname" \
    < "${TMPDIR}/install/mysql.sql"
rm -Rf "${TMPDIR}/install"

# Copy and set Wallabag configuration
wb_conf="${TMPDIR}/inc/poche/config.inc.php"
cp ../conf/config.inc.php "$wb_conf"
sed -i "s@#DBNAME#@${dbname}@g" "$wb_conf"
sed -i "s@#DBUSER#@${dbuser}@g" "$wb_conf"
sed -i "s@#DBPASS#@${dbpass}@g" "$wb_conf"
sed -i "s@#DESKEY#@${deskey}@g" "$wb_conf"

# Install files and set permissions
sudo mv "$TMPDIR" "$DESTDIR"
sudo chown -R www-data: "$DESTDIR"

# Copy and set nginx configuration
# TODO: Check path variable
nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
sed -i "s@#LOCATION#@${path:-/}@g" ../conf/nginx.conf
sed -i "s@#DESTDIR#@${DESTDIR}@g"  ../conf/nginx.conf
sudo cp ../conf/nginx.conf "$nginx_conf"

# Add users to Wallabag
user_id=1
for username in $(ynh_user_list); do
    user_pass=$(ynh_string_random)
    ynh_mysql_connect_as $dbuser $dbpass $dbname << EOF
INSERT INTO users (id,username,password,name,email)
  VALUES (${user_id},'${username}','${user_pass}','${username}','');
INSERT INTO users_config (user_id,name,value)
  VALUES ('${user_id}','language','en_EN.utf8');
INSERT INTO users_config (user_id,name,value)
  VALUES ('${user_id}','pager','10');
EOF
    ((user_id++))
done

# Set app name in hooks
sed -i "s@#APP#@${app}@g" ../hooks/post_user_create

# Save app settings
ynh_app_setting_set "$app" mysqlpwd "$dbpass"

# Set SSOwat rules
ynh_app_setting_set "$app" unprotected_uris "/"

# Reload services
sudo service nginx reload || true
