#!/bin/bash

# Retrieve arguments
app=${!#}

# Load common variables and helpers
source ./_common.sh

# Set app specific variables
dbname=$app
dbuser=$app

# Drop MySQL database and user
ynh_mysql_drop_db $dbname || true
ynh_mysql_drop_user $dbuser || true

# Retrieve domain from app settings
domain=$(ynh_app_setting_get $app domain)

# Delete app directory and configurations
sudo rm -rf "/var/www/${app}"
[[ -n $domain ]] && sudo rm -f "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Reload services
sudo service nginx reload || true
