#!/bin/bash

db_user=poche
db_name=poche
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting poche domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
sudo rm -rf /var/www/poche
sudo rm -f /etc/nginx/conf.d/$domain.d/poche.conf
